### PR TITLE
Switch user to users group

### PR DESCRIPTION
**Pull request by pivnicek**
story https://keboola.atlassian.net/browse/PS-24

### CODE REVIEW

**Comment by pivnicek** [comment]
You're very trusting :-).  I've chgrp'd the data folder just to be on the safe side.

**Comment by odinuv** [comment]
not sure if that is a good idea - the Rserver might like to write something in there

**Comment by pivnicek** [comment]
It still can, it's all 7s

**Comment by odinuv** [comment]
ok

**Pull request merged**
